[build-system]
# See https://github.com/scipy/scipy/pull/10431 for the AIX issue.
requires = [
  "setuptools>=19.6",
  "wheel",
  # cython version is imposed by that of numpy, see release notes
  # https://github.com/numpy/numpy/releases/tag/v1.18.4
  "Cython>=0.29.15",
  "numpy>=1.18.4; platform_system!='AIX'",
]

# To be kept consistent with "Code Style" section in CONTRIBUTING.rst
[tool.black]
line-length = 88
target-version = ['py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | yt/frontends/stream/sample_data
)/
| yt/visualization/_colormap_data.py
'''


# To be kept consistent with "Import Formatting" section in CONTRIBUTING.rst
[tool.isort]
profile = "black"
combine_as_imports = true
skip =  ["venv", "benchmarks"]
known_third_party = [
  "IPython",
  "nose",
  "numpy",
  "sympy",
  "matplotlib",
  "unyt",
  "git",
  "yaml",
  "dateutil",
  "requests",
  "coverage",
  "pytest",
  "pyx",
  "glue",
]
known_first_party = ["yt"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
